blank_issues_enabled: true
contact_links:
  - name: 💬 Diskusi Umum
    url: https://github.com/zhal2810/war-era-test/discussions
    about: Untuk pertanyaan umum, ide awal, atau diskusi seputar API WarEra yang belum terdokumentasi resmi.
